---
- name: Update yum package list.
  yum:
    name: '*'
    state: latest
    update_cache: yes
- name: Install required packages. (show https://github.com/rbenv/ruby-build/wiki#suggested-build-environment)
  yum:
    name:
      - git
      - gcc
      - bzip2
      - openssl-devel
      - libyaml-devel
      - libffi-devel
      - readline-devel
      - zlib-devel
      - gdbm-devel
      - ncurses-devel
- name: Install rbenv.
  become_user: "{{ user }}"
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv
    accept_hostkey: yes
- name: Add PATH of rbenv.
  become_user: "{{ user }}"
  shell: |
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
    echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
- name: Create directory of ruby-build.
  become_user: "{{ user }}"
  file:
    path: ~/.rbenv/plugins
    state: directory
- name: Install ruby-build.
  become_user: "{{ user }}"
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
    accept_hostkey: yes
- name: Install ruby-{{ ruby_version }}.
  become_user: "{{ user }}"
  shell: |
    source ~/.bash_profile
    rbenv install {{ ruby_version }}
    rbenv global {{ ruby_version }}
