---
- name: Add docker repository.
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
- name: Update yum package list.
  yum:
    name: '*'
    state: latest
    update_cache: yes
- name: Install docker packages.
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
- name: Install docker-compose command. (show http://docs.docker.jp/compose/install.html)
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: 0755
- name: Start docker on boot.
  service:
    name: docker
    enabled: yes
- name: Append {{ user }} user to docker group.
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
- name: Restart docker service.
  service:
    name: docker
    state: restarted
