---
- name: Add docker repository.
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
- name: Update yum package list.
  yum:
    name: '*'
    state: latest
    update_cache: yes
- name: Install docker packages.
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
- name: Install docker-compose command. (show http://docs.docker.jp/compose/install.html)
  shell: |
    curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose
- name: Start docker on boot.
  service:
    name: docker
    enabled: yes
- name: Append vagrant user to docker group.
  user:
    name: vagrant
    groups: docker
    append: yes
- name: Restart docker service.
  service:
    name: docker
    state: restarted
